### ISSUE TITLE
上下位机一体化精度测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/HV_YOLO#11]
要求：
１．easyai库评测接口
２．设计测试流程
３．编写下位机测试程序

**Comment by foww-0001** [comment]
Fix: 
1. ClassNET_tool.sh中mean=129.3041,124.0699,112.4340; scale=67.9934
2. easyai/config/task/classify_config中self.data_std = (0.2666410733740041, 0.2666410733740041, 0.2666410733740041）
@lpj0822

**Comment by foww-0001** [comment]
### 上下位机精度不一致解决方法

* 使用安霸最新的转换工具进行测试
* 分类中存在多个最终输出数组很小，由此导致量化结果很差
* 使用参数量较小的网络进行模型训练
* 冻住bn层进行训练
* 使用半精度浮点型进行训练
* 数据扩充，防止模型过拟合
@lpj0822

**Comment by lpj0822** [comment]
### 测试要求
* cls 、det2d、seg，把存上位机结果测试
* amba sdk安装流程，编写文档
* 上下机模型对比工具加入shell脚本，输出对比结果
* 整理上下位机模型对比方法的流程（精度对比，模型数值对比等）
@foww-0001

**Comment by foww-0001** [comment]
Fix：目前发现下位机测试代码里面有两个错误：1. 输入图像是rgb，但是opencv读入是bgr，这里没有做转换;2. 寻找最大值代码有误，已改正
@lpj0822

**Comment by foww-0001** [comment]
Traceback (most recent call last):
  File "easyai/inference_task.py", line 56, in <module>
    main()
  File "easyai/inference_task.py", line 45, in main
    inference_task.classify_task(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 22, in classify_task
    cls.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify.py", line 25, in process
    self.task_config.image_channel)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_inference.py", line 54, in get_image_data_lodaer
    dataloader = TextDataLoader(input_path, image_size, data_channel)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/text_data_loader.py", line 19, in __init__
    raise Exception("Invalid path!", input_path)
Exception: ('Invalid path!', '/home/wfw/data/VOCdevkit/animals10_classify_small/ImageSets/val.txt')

**Comment by foww-0001** [comment]
Traceback (most recent call last):
  File "easyai/inference_task.py", line 56, in <module>
    main()
  File "easyai/inference_task.py", line 45, in main
    inference_task.classify_task(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 22, in classify_task
    cls.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify.py", line 25, in process
    self.task_config.image_channel)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_inference.py", line 54, in get_image_data_lodaer
    dataloader = TextDataLoader(input_path, image_size, data_channel)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/text_data_loader.py", line 19, in __init__
    raise Exception("Invalid path!", input_path)
Exception: ('Invalid path!', '/home/wfw/data/VOCdevkit/animals10_classify_small/ImageSets/val.txt')
@lpj0822

**Comment by foww-0001** [comment]
cls测试流程跑通，出现以下问题：
1. cls输出的格式有问题， ”tensor([0], device='cuda:0')“， 没有文件名称，类别格式有误
2. 精度输出有误，“Classify Accuracy: %.5f 0.17”

**Comment by foww-0001** [comment]
目前测试精度有差别，精度应该是80%左右，测试得到的精度为17%，需要继续调整。

**Comment by foww-0001** [comment]
easyai offline test修改内容已经提交到dev_wfw，有空尽快合并。
@lpj0822

**Comment by foww-0001** [comment]
修改offiline classify test输出形式为百分比形式：Classify Accuracy: 91.500%
@lpj0822

**Comment by lpj0822** [comment]
不要用百分比，用实际数据输出，小数

**Comment by foww-0001** [comment]
已经上传了
@lpj0822

**Comment by foww-0001** [comment]
因为你的classify_test测试里面就是用的百分比，可以看一下，prec1: 62.06896551724138，如果不需要就忽略这个修改
@lpj0822

**Comment by foww-0001** [comment]
### 检测offline中的一些问题
1. 检测的test中没有建立save_result_dir，因此报错：FileNotFoundError: [Errno 2] No such file or directory: './.log/det2d_results/pear.txt'
2. 运行offline_det2d_evaluation.py出错：
(edgeENV) wfw@wfw-W560-G30:~/EDGE/HV_YOLO$ python easyai/tools/offline_det2d_evaluation.py -i .log/det2d_results/ -t '/home/wfw/data/VOCdevkit/Fruit_detection/ImageSets/val.txt' -c '/home/wfw/detection2d_config.json' 
start...
.log/det2d_results
Traceback (most recent call last):
  File "easyai/tools/offline_det2d_evaluation.py", line 33, in <module>
    main()
  File "easyai/tools/offline_det2d_evaluation.py", line 28, in main
    mAP, _ = test.process(options.inputPath, options.targetPath)
  File "easyai/tools/offline_det2d_evaluation.py", line 18, in process
    mAP, aps = self.evaluator.result_eval(test_path, target_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 39, in result_eval
    detect_boxes = self.get_detect_boxes(result_path, name)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 86, in get_detect_boxes
    for line_data in self.dir_process.getFileData(result_path):
  File "/home/wfw/EDGE/HV_YOLO/easyai/helper/dirProcess.py", line 20, in getFileData
    with open(dataFilePath, 'r') as file:
IsADirectoryError: [Errno 21] Is a directory: '.log/det2d_results'

**Comment by lpj0822** [comment]
-i 是inference跑出来的结果，不是test跑出来的结果

**Comment by foww-0001** [comment]
我运行了inference，vim .log/det2d_result.txt，内容如下：
./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt./.log/det2d_result.txt

代码文件写入有误：file.write(self.task_config.save_result_path)，已解决，得到：
f63.jpg|pear 0.9776066541671753 84.40187424879808 1239.7714339036208 2723.573955829327|
@lpj0822

**Comment by foww-0001** [comment]
运行offline_det2d_evaluation.py出现新错误：
Traceback (most recent call last):
  File "easyai/tools/offline_det2d_evaluation.py", line 33, in <module>
    main()
  File "easyai/tools/offline_det2d_evaluation.py", line 28, in main
    mAP, _ = test.process(options.inputPath, options.targetPath)
  File "easyai/tools/offline_det2d_evaluation.py", line 18, in process
    mAP, aps = self.evaluator.result_eval(test_path, target_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 39, in result_eval
    detect_boxes = self.get_detect_boxes(result_path, name)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 87, in get_detect_boxes
    filename_post = split_datas[0].strip()
AttributeError: 'list' object has no attribute 'strip'
@lpj0822

**Comment by foww-0001** [comment]
split_datas = [x.strip().split('|') for x in line_data if x.strip()]
print(split_datas)
打印这一行得到：
[['f'], ['6'], ['3'], ['.'], ['j'], ['p'], ['g'], ['', ''], ['p'], ['e'], ['a'], ['r'], ['0'], ['.'], ['9'], ['7'], ['7'], ['6'], ['0'], ['6'], ['6'], ['5'], ['4'], ['1'], ['6'], ['7'], ['1'], ['7'], ['5'], ['3'], ['8'], ['4'], ['.'], ['4'], ['0'], ['1'], ['8'], ['7'], ['4'], ['2'], ['4'], ['8'], ['7'], ['9'], ['8'], ['0'], ['8'], ['1'], ['2'], ['3'], ['9'], ['.'], ['7'], ['7'], ['1'], ['4'], ['3'], ['3'], ['9'], ['0'], ['3'], ['6'], ['2'], ['0'], ['8'], ['2'], ['7'], ['2'], ['3'], ['.'], ['5'], ['7'], ['3'], ['9'], ['5'], ['5'], ['8'], ['2'], ['9'], ['3'], ['2'], ['7'], ['', '']]
@lpj0822

**Comment by lpj0822** [comment]
split_datas = [x.strip() for x in line_data.split('|') if x.strip()]

**Comment by foww-0001** [comment]
start...
Mean AP = 0.0000
~~~~~~~~
Results:
orange: 0.000
pear: 0.000
apple: 0.000
potato: 0.000
mAP: 0.000
~~~~~~~~
End of game, have a nice day!
结果为0.0
@lpj0822

**Comment by foww-0001** [comment]
1. 检测少保存一位，save_data = save_data + "{} {} {} {} {}|".format(temp_object.name, confidence,
                                                                 x1, y1, x2, y2)
2. box_datas = [x.strip().split(' ') for x in temp_box if x.strip()] 出错，改为box_datas = [x.strip() for x in temp_box.split(' ') if x.strip()]
3. ValueError: invalid literal for int() with base 10: '792.8920335036057'， 由int(box_datas[2]) 改为 float(box_datas[2])
最终结果正确。
修改已经上传。
@lpj0822

**Comment by foww-0001** [comment]
分割offline测试结果正常！

start...
Overall Acc: 	 0.9996478571428571
FreqW Acc : 	 0.9993306600367391
Mean IoU : 	 0.7876895931033363
Mean Acc : 	 0.8194431385205584
End of game, have a nice day!

测试要求第1点和第2点完成！！！

@lpj0822

**Comment by foww-0001** [comment]
分类inference需要考虑把均值和方差算进去！！！
@lpj0822

**Comment by lpj0822** [comment]
修改完成

**Comment by foww-0001** [comment]
分类inference还是结果错误，查看到几个问题：
1. 分类训练中没有进行image_resize_square，而是直接对图片进行resize，但是inference中用了image_resize_square
2. 分类训练中进行了image_normalize（除以255.0）,并做了归一化操作，但是inference只做了归一化操作
@lpj0822

**Comment by lpj0822** [comment]
以上问题，需要调整代码结构，目前已经修改完成
@foww-0001

**Comment by lpj0822** [comment]
先看看这快，还有没有其他问题
@foww-0001

**Comment by foww-0001** [comment]
分类测试报错，错误如下：
```
process start...
Using device: "cuda"
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 25, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify.py", line 25, in process
    dataloader = self.get_image_data_lodaer(input_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_inference.py", line 55, in get_image_data_lodaer
    normalize_type = self.task_config.self.normalize_type
AttributeError: 'ClassifyConfig' object has no attribute 'self'
```
删除self，继续运行，报错：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 25, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify.py", line 26, in process
    for index, (file_path, src_image, image) in enumerate(dataloader):
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/text_data_loader.py", line 45, in __next__
    mean=self.mean, std=self.std)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/image_dataset_process.py", line 34, in normalize
    mean = float(param['mean'])
TypeError: float() argument must be a string or a number, not 'tuple'
```
出现冲突，mean是tuple or number
@lpj0822

**Comment by lpj0822** [comment]
带已经修改，并提交
@foww-0001

**Comment by foww-0001** [comment]
分类结果正确：
```
 /home/wfw/classify_config.json 
start...
Classify Accuracy: 94.000%
End of game, have a nice day!
```
检测测试报错：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 24, in infer
    task.load_weights(weight_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_inference.py", line 44, in load_weights
    self.torchModelProcess.loadLatestModelWeight(weights_path, self.model)
  File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/torch_model_process.py", line 56, in loadLatestModelWeight
    model.load_state_dict(checkpoint['model'])
  File "/home/wfw/EDGE/edgeENV/lib/python3.5/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloV3Det2d:
	size mismatch for convActivationBlock_7.block.convolutional.weight: copying a param with shape torch.Size([27, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 1024, 1, 1]).
	size mismatch for convActivationBlock_7.block.convolutional.bias: copying a param with shape torch.Size([27]) from checkpoint, the shape in current model is torch.Size([45]).
	size mismatch for convActivationBlock_19.block.convolutional.weight: copying a param with shape torch.Size([27, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 512, 1, 1]).
	size mismatch for convActivationBlock_19.block.convolutional.bias: copying a param with shape torch.Size([27]) from checkpoint, the shape in current model is torch.Size([45]).
	size mismatch for convActivationBlock_31.block.convolutional.weight: copying a param with shape torch.Size([27, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 256, 1, 1]).
	size mismatch for convActivationBlock_31.block.convolutional.bias: copying a param with shape torch.Size([27]) from checkpoint, the shape in current model is torch.Size([45]).
```
类别错误
@lpj0822

**Comment by lpj0822** [comment]
config文件是怎样的？
@foww-0001

**Comment by foww-0001** [comment]
offiline运行报错：
```
Traceback (most recent call last):
  File "easyai/tools/offline_det2d_evaluation.py", line 33, in <module>
    main()
  File "easyai/tools/offline_det2d_evaluation.py", line 27, in main
    test = OfflineDet2dEvaluation(task_config.class_name)
AttributeError: 'Detect2dConfig' object has no attribute 'class_name'
```
class_name改为detect2d_class
@lpj0822

**Comment by MiniBullLab** [comment]
目前分类，检测，分割的离线测试都测试通过，没有问题。
@lpj0822

**Comment by foww-0001** [comment]
目前，分类，检测，分割的离线检测都测试通过，没有问题。
@lpj0822

**Comment by foww-0001** [comment]
多GPU训练会报错，需在运行运行代码之前加上CUDA_VISIBLE_DEVICES=0，保证代码运行在单GPU上。
@lpj0822

**Comment by foww-0001** [comment]
### caltech257上下位机精度对比：
* resnet18
** PC 63.4%
** AMBA 61.7%

**Comment by foww-0001** [comment]
### 汽车划痕上的精度测试
同时使用threshold为0.5的比对：
得到：
PC 71.2%
PC offline 63.7%
AMBA 51.3%

**Comment by foww-0001** [comment]
### 水果检测的精度测试：
PC：0.9875
AMBA：0.9767

**Comment by foww-0001** [comment]
### caltech100上下位机精度对比：
PC：90.15%
AMBA：89.72%
