### ISSUE TITLE
easyai loss测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/HV_YOLO#13]
要求：
１．yolov2训练与推断没有问题
２．ssd训练与推断没有问题
３．其他loss运行没有问题

**Comment by foww-0001** [comment]
Ubuntu16.04安装requirements_tools.txt后，运行easy_tools/easy_main.py，报错：
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

已放弃 (核心已转储)
@lpj0822

**Comment by MiniBullLab** [comment]
以上问题不属于这个issues
@foww-0001

**Comment by foww-0001** [comment]
问题已经移到相应issus下
@lpj0822

**Comment by foww-0001** [comment]
训练yolov2时报错，训练命令是
python3 easyai/train_task.py -t detect2d -i /home/wfw/data/VOCdevkit/BKLdata/ImageSets/train.txt -v /home/wfw/data/VOCdevkit/BKLdata/ImageSets/val.txt -m ./cfg/det2d/yolov2.cfg -p /home/wfw/HASCO/all_wights/yolov2_coco.pt
错误如下：
Loading pretainModel from /home/wfw/HASCO/all_wights/yolov2_coco.pt
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 67, in train
    self.load_latest_param(self.train_task_config.latest_weights_file)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 48, in load_latest_param
    self.train_task_config.freeze_layer_type)
  File "/home/wfw/EDGE/HV_YOLO/easyai/solver/torch_optimizer.py", line 29, in freeze_optimizer_layer
    self.createOptimizer(epoch, model, base_lr)
  File "/home/wfw/EDGE/HV_YOLO/easyai/solver/torch_optimizer.py", line 39, in createOptimizer
    filter(lambda p: p.requires_grad, model.parameters()), lr=base_lr)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/optim/optimizer.py", line 45, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

**Comment by foww-0001** [comment]
修改config文件下task/detect2d_config.py中self.freeze_layer_type = 1改为=0报错消失。

**Comment by foww-0001** [comment]
修改完后继续运行有报错：
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 108, in compute_loss
    loss = self.model.lossList[0](output_list[0], targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/region2d_loss.py", line 130, in forward
    conf = conf.transpose(2, 3).contiguous().view(batch_size, -1, 1)
RuntimeError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

修改region2d_loss.py中conf = conf.transpose(2, 3).contiguous().view(batch_size, -1, 1)改为conf = conf.view(batch_size, -1, 1)即可开始跑训练。

**Comment by lpj0822** [comment]
代码已经修改
@foww-0001

**Comment by foww-0001** [comment]
拉取最新代码后，跑detect inference出错，运行命令为：
python easyai/inference_task.py -t detect2d -i /home/wfw/data/VOCdevkit/BKLdata/ImageSets/val.txt -m ./cfg/det2d/yolov2.cfg -w .log/snapshot/det2d_best.pt -c .log/config/detection2d_config.jsonn easyai/inference_task.py -t detect2d -i /home/wfw/data/VOCdevkit/BKLdata/ImageSets/val.txt -m ./cfg/det2d/yolov2.cfg -w .log/snapshot/det2d_best.pt -c .log/config/detection2d_config.json
错误如下：
Traceback (most recent call last):
  File "easyai/inference_task.py", line 56, in <module>
    main()
  File "easyai/inference_task.py", line 47, in main
    inference_task.detect2d_task(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 27, in detect2d_task
    det2d.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d.py", line 30, in process
    for i, (file_path, src_image, img) in enumerate(dataloader):
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/text_data_loader.py", line 44, in __next__
    ratio, pad_size = self.dataset_process.get_square_size(src_size, self.image_size)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/image_dataset_process.py", line 72, in get_square_size
    ratio = min(float(dst_size[0]) / src_size[0], float(dst_size[1]) / src_size[1])
TypeError: float() argument must be a string or a number, not 'tuple'

**Comment by foww-0001** [comment]
去掉base_inference.py中的image_size = self.task_config.image_size,后面那个逗号，解决问题。
@lpj0822

**Comment by foww-0001** [comment]
### yolov2训练与推断
目前yolov2训练与推断都没有问题，但是精度很低，mAP只有3%，需要进一步找问题。
修改代码以上传分支dev_wfw
@lpj0822

**Comment by foww-0001** [comment]
ssd跑训练时报，错误如下：
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 30, in detect2d_train
    det2d_train = Detection2dTrain(cfg_path, gpu_id, config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 23, in __init__
    self.model = self.torchModelProcess.initModel(self.model_args, gpu_id)
  File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/torch_model_process.py", line 23, in initModel
    model = self.modelFactory.get_model(model_config)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 28, in get_model
    result = self.get_model_from_cfg(input_name, model_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 43, in get_model_from_cfg
    model = MyModel(model_define, path, default_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/my_model.py", line 24, in __init__
    self.create_block_list()
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/my_model.py", line 29, in create_block_list
    backbone_block, self.backbone_name = self.creat_backbone()
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/my_model.py", line 70, in creat_backbone
    result = self.backbone_factory.get_base_model(input_cfg_path, self.default_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/backbone/utility/backbone_factory.py", line 55, in get_base_model
    result = self.get_backbone_from_cfg(input_name)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/backbone/utility/backbone_factory.py", line 66, in get_backbone_from_cfg
    model = MyBackbone(model_define)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/backbone/utility/my_backbone.py", line 16, in __init__
    self.create_block_list()
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/backbone/utility/my_backbone.py", line 22, in create_block_list
    self.createTaskList.createOrderedDict(self.model_defines, base_out_channels)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/create_model_list.py", line 77, in createOrderedDict
    self.create_convolutional(block_def)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/create_model_list.py", line 180, in create_convolutional
    assert pad == ((kernel_size - 1) // 2)
@lpj0822

**Comment by foww-0001** [comment]
1. 暂时注释掉assert pad == ((kernel_size - 1) // 2)继续运行报出以下错误：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 135, in forward
    self.ssd_priorbox.set_anchor_param(self.anchor_counts[index],
TypeError: 'generator' object is not subscriptable
```
打印self.anchor_counts得到：
```
anchor_counts: <generator object CreateModuleList.create_loss.<locals>.<genexpr> at 0x7f61eb857ba0>
```
查看代码中使用anchor_counts的获得方式：
```
anchor_counts  = （int(x) for x in module_def['anchor_counts'].split(',') if x.strip()）
```
修改为
```
anchor_counts = [int(x) for x in module_def['anchor_counts'].split(',') if x.strip()]
```
依次修改input_size等其余变量可以继续运行。
@lpj0822

**Comment by foww-0001** [comment]
* 继续运行报错，错误如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 154, in forward
    loc_targets, cls_targets = self.build_targets(targets, prior_boxes)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 102, in build_targets
    iou = torch_corners_box2d_ious(gt_boxes, tem_boxes)
  File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/box_utility.py", line 59, in torch_corners_box2d_ious
    box2[:, :2].unsqueeze(0).expand(N, M, 2)   # [M,2] -> [1,M,2] -> [N,M,2]
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'other'
```
打印发现gt_boxes跑在cpu上，首先获取output的device：
```
device = prediction_list[0].device
```
在使用到后面的变量中：
```
gt_boxes = gt_boxes.to(device)
```
* 接着报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 155, in forward
    loc_targets, cls_targets = self.build_targets(targets, prior_boxes)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 106, in build_targets
    loc, cls_conf = self.encode(boxes, labels)
TypeError: encode() missing 1 required positional argument: 'prior_boxes'
```
加入prior_boxes：
```
dets_loc, dets_cls = self.decode(loc_preds, cls_preds, prior_boxes)
```
* 继续运行报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 168, in forward
    cls_loss = self.cross_entropy_loss(cls_preds.view(-1, self.num_classes),
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'MultiBoxLoss' object has no attribute 'num_classes'
```
没有num_classes变量，改为变量class_number。

* 继续运行报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 169, in forward
    cls_targets.view(-1))  # [N*8732,]
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 64, in cross_entropy_loss
    return log_sum_exp.view(-1, 1) - x.gather(1, y.view(-1, 1))
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'
```
同样y跑在cpu上，修改：
```
return torch.stack(target_boxes, 0).to(device), torch.stack(target_labels, 0).to(device)
```
* 继续运行报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 84, in train
    loss = self.compute_backward(images, targets, i)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 93, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 110, in compute_loss
    loss = self.model.lossList[0](output_list, targets)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 169, in forward
    cls_targets.view(-1))  # [N*8732,]
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 65, in cross_entropy_loss
    return log_sum_exp.view(-1, 1) - x.gather(1, y.view(-1, 1))
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index'
```
修改变量类型，float改为long:
```
return torch.stack(target_boxes, 0).to(device), torch.stack(target_labels, 0).long().to(device)
```
可以训练ssd，但是结果为None：
```
Epoch: 0[0/157]	 Loss: nan	 Rate: 0.0000000 	 Time: 8.62417	
Epoch: 0[1/157]	 Loss: nan	 Rate: 0.0000000 	 Time: 0.94222	
Epoch: 0[2/157]	 Loss: nan	 Rate: 0.0000000 	 Time: 0.98951	
```
还有看到所有yolov3_loss的loss都放到gpu上的：
```
        # criteria
        self.mse_loss = self.mse_loss.to(device)
        self.bce_loss = self.bce_loss.to(device)
        self.smooth_l1_loss = self.smooth_l1_loss.to(device)
        self.ce_loss = self.ce_loss.to(device)
```
但是multibox_loss却没有，是否需要修改。

**Comment by foww-0001** [comment]
DetectionTrainDataloader中的target如下表示：
```
result[index, :] = np.array([class_id, x, y, width, height])
```
因此是x,y,w,h,所以
```
wh = (gt_boxes[:, 2:] - gt_boxes[:, :2]) / prior_boxes[:, 2:]  # [8732,2]
```
无需再减去x,y，直接改为：
```
wh = gt_boxes[:, 2:] / prior_boxes[:, 2:]
```
输出正常的loss:
```
Epoch: 0[0/157]	 Loss: 5.0222464	 Rate: 0.0000000 	 Time: 8.75004	
Epoch: 0[1/157]	 Loss: 5.1045146	 Rate: 0.0000000 	 Time: 0.94841	
Epoch: 0[2/157]	 Loss: 5.1833033	 Rate: 0.0000000 	 Time: 1.00902	
Epoch: 0[3/157]	 Loss: 5.6261112	 Rate: 0.0000000 	 Time: 0.94516
```
@lpj0822

**Comment by foww-0001** [comment]
### ssd训练与推断
ssd训练目前可以正常运行，效果需要进一步检验，代码已上传。
@lpj0822

**Comment by foww-0001** [comment]
ssd test 报错，错误如下：
1/500 Traceback (most recent call last):
  File "easyai/train_task.py", line 77, in <module>
    main()
  File "easyai/train_task.py", line 68, in main
    train_task.detect2d_train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 32, in detect2d_train
    det2d_train.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 88, in train
    self.test(val_path, epoch, save_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 151, in test
    mAP, aps = self.detect_test.test(val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_test.py", line 39, in test
    result = self.detect_inference.infer(input_image, self.threshold_det)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d.py", line 77, in infer
    output = self.compute_output(output_list)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d.py", line 94, in compute_output
    temp = self.model.lossList[i](output_list[i])
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/HV_YOLO/easyai/loss/det2d/multibox_loss.py", line 126, in forward
    N, C, H, W = y_loc.size()
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by foww-0001** [comment]
ssd 训练了100epoch后loss由5.5掉到1.0左右，
但是精度依旧为0
```
Mean AP = 0.0000
~~~~~~~~
Results:
bike: 0.000
bus: 0.000
car: 0.000
motor: 0.000
person: 0.000
rider: 0.000
traffic light: 0.000
traffic sign: 0.000
train: 0.000
truck: 0.000
mAP: 0.000
~~~~~~~~
```
还是需要进一步查看精度问题。

**Comment by foww-0001** [comment]
拉取最新代码，报错下：：
process start...
This task(detect2d) not exits!
process end!
@lpj0822

**Comment by lpj0822** [comment]
该bug已经修改，注册没有注册进去，代码已经提交
@foww-0001

**Comment by foww-0001** [comment]
拉取最新代码，报错：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 26, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 90, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 20, in __init__
    super().__init__(cfg_path, config_path, TaskName.Detect2d_Task)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_train.py", line 32, in __init__
    "data_channel": self.train_task_config.image_channel
AttributeError: 'Detect2dConfig' object has no attribute 'image_channel'
```
```
Using device: "cuda"
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 26, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 90, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 28, in __init__
    self.detect_test = Detection2dTest(cfg_path, gpu_id, config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_test.py", line 19, in __init__
    self.detect_inference = Detection2d(cfg_path, gpu_id, config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d.py", line 19, in __init__
    super().__init__(cfg_path, config_path, TaskName.Detect2d_Task)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_inference.py", line 28, in __init__
    "data_channel": self.task_config.image_channel
AttributeError: 'Detect2dConfig' object has no attribute 'image_channel'
```
修改"data_channel": self.task_config.image_channel中image_chanel改为data_channel

**Comment by foww-0001** [comment]
继续运行，报错：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 26, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 90, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 20, in __init__
    super().__init__(cfg_path, config_path, TaskName.Detect2d_Task)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_train.py", line 26, in __init__
    self.train_task_config = self.config_factory.get_config(self.task_name, self.config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/config/utility/config_factory.py", line 20, in get_config
    result.load_config(config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/config/utility/image_task_config.py", line 37, in load_config
    self.load_data_value(config_dict)
  File "/home/wfw/EDGE/HV_YOLO/easyai/config/task/detect2d_config.py", line 37, in load_data_value
    self.load_image_data_value(config_dict)
  File "/home/wfw/EDGE/HV_YOLO/easyai/config/utility/image_task_config.py", line 63, in load_image_data_value
    self.data_mean = tuple(config_dict['data_mean'])
TypeError: 'int' object is not iterable
```
修改image_task_config.py中
```
self.data_mean = (0, 0, 0)
self.data_std = (1, 1, 1)
```
修改anchors的参数：
```
anchor_sizes = 0.57273, 0.677385|1.87446, 2.06253|3.33843, 5.47434|7.88282, 3.52778|9.77052, 9.16828
```
继续运行。

**Comment by foww-0001** [comment]
运行测试报错：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 28, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 83, in train
    self.test(val_path, epoch, save_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 146, in test
    mAP, aps = self.detect_test.test(val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_test.py", line 32, in test
    for i, (image_path, src_image, input_image) in enumerate(dataloader):
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/det2d/det2d_val_dataloader.py", line 29, in __getitem__
    self.image_size)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/det2d/det2d_dataset_process.py", line 48, in resize_src_image
    pad_color=self.pad_color)
ValueError: too many values to unpack (expected 1)
```
修改det2d_dataset_process.py下面：
```
image, = self.dataset_process.image_resize_square(src_image, ratio, pad_size,
                                                          pad_color=self.pad_color)
```
中逗号去掉。

以上修改已上传。
@lpj0822

**Comment by MiniBullLab** [comment]
anchor_sizes是哪的？
@foww-0001

**Comment by foww-0001** [comment]
yolov2的anchor_sizes
@lpj0822

**Comment by foww-0001** [comment]
运行检测test出错：
```
Using device: "cuda"
/home/wfw/EDGE/edgeENV/lib/python3.5/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
/home/wfw/EDGE/edgeENV/lib/python3.5/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 25, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d.py", line 32, in process
    for i, (file_path, src_image, img) in enumerate(dataloader):
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/text_data_loader.py", line 43, in __next__
    pad_color=self.image_pad_color)
  File "/home/wfw/EDGE/HV_YOLO/easyai/data_loader/utility/image_dataset_process.py", line 22, in resize
    pad_color = int(param['pad_color'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```
@lpj0822

**Comment by lpj0822** [comment]
代码修改，提交
@foww-0001

**Comment by foww-0001** [comment]
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 28, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 62, in train
    self.load_latest_param(self.train_task_config.latest_weights_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/det2d/detect2d_train.py", line 50, in load_latest_param
    self.train_task_config.freeze_layer_type)
  File "/home/wfw/EDGE/HV_YOLO/easyai/solver/torch_optimizer.py", line 29, in freeze_optimizer_layer
    self.createOptimizer(epoch, model, base_lr)
  File "/home/wfw/EDGE/HV_YOLO/easyai/solver/torch_optimizer.py", line 39, in createOptimizer
    filter(lambda p: p.requires_grad, model.parameters()), lr=base_lr)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/optim/optimizer.py", line 45, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```
@lpj0822

**Comment by foww-0001** [comment]
### yolov2训练与推断
1. 因为region2d_loss中anchor_sizes需要去除以reduction：
```
self.anchor_sizes = self.anchor_sizes / float(self.reduction)
```
所以cfg中的anchor_sizes要乘以reduction：
```
anchor_sizes = 18.32736,21.67632|59.98272,66.00096|106.82976,175.17888|252.25024,112.88896|312.65664, 293.38496
```

2. 对比原始的loss中，少了size_average=False的参数，加上：
```
self.mse = nn.MSELoss(size_average=False)
self.ce = nn.CrossEntropyLoss(size_average=False)
```

最终训练精度如下：
```
Results:
bike: 0.118
bus: 0.229
car: 0.323
motor: 0.091
person: 0.097
rider: 0.113
truck: 0.228
mAP: 0.171
```
效果有待提升。

inference正常可以检出目标。
@lpj0822

**Comment by foww-0001** [comment]
代码已上传，请尽快合并。
@lpj0822

**Comment by lpj0822** [comment]
代码已经上传
@foww-0001
