### ISSUE TITLE
easy_tools测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/HV_YOLO#14]
1.界面训练模型测试

**Comment by foww-0001** [comment]
Ubuntu16.04安装requirements_tools.txt后，运行easy_tools/easy_main.py，报错：
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

已放弃 (核心已转储)
@lpj0822

**Comment by lpj0822** [comment]
安装：
```
sudo apt-get install libxcb-xinerama0
```

**Comment by foww-0001** [comment]
安装完sudo apt-get install libxcb-xinerama0后可以正常运行
@lpj0822

**Comment by foww-0001** [comment]
运行一个两类的数据集，出现错误：
classify start train!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 82, in <module>
    train_main()
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 61, in train_main
    train_task.classify_train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 26, in classify_train
    cls_train_task.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify_train.py", line 66, in train
    self.load_latest_param(self.train_task_config.latest_weights_file)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify_train.py", line 35, in load_latest_param
    checkpoint = self.torchModelProcess.loadLatestModelWeight(latest_weights_path, self.model)
  File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/torch_model_process.py", line 56, in loadLatestModelWeight
    model.load_state_dict(checkpoint['model'])
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MyModel:
	size mismatch for fcLayer_2.linear.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([100, 512]).
	size mismatch for fcLayer_2.linear.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([100]).
@lpj0822

**Comment by foww-0001** [comment]
删除snapshot后运行正常
@lpj0822

**Comment by foww-0001** [comment]
1. 训练到一半想要换个新的数据训练，发现没有从头开始训练，而是继续训练。
2. 训练显示很卡，占用CPU到70%左右
@lpj0822

**Comment by foww-0001** [comment]
模型转换报错：
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 82, in <module>
    train_main()
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 61, in train_main
    train_task.classify_train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 27, in classify_train
    self.image_model_convert(cls_train_task, cls_train_task.model_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 58, in image_model_convert
    train_task.train_task_config.snapshot_dir)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/model_to_onnx.py", line 28, in model_convert
    model = self.model_factory.get_model(model_config)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 24, in get_model
    input_name = model_config['type'].strip()
KeyError: 'type'
@lpj0822

**Comment by foww-0001** [comment]
分割界面训练时模型转换时和分类报同样的错误！
检测界面模型转换报以下错误：
Usage: easy_convert.py [options]

easy_convert.py: error: Could not find the input file
process start...

@lpj0822

**Comment by lpj0822** [comment]
> 运行一个两类的数据集，出现错误：
> classify start train!
> Traceback (most recent call last):
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 82, in
> train_main()
> File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 61, in train_main
> train_task.classify_train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
> File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 26, in classify_train
> cls_train_task.train(self.train_path, self.val_path)
> File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify_train.py", line 66, in train
> self.load_latest_param(self.train_task_config.latest_weights_file)
> File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify_train.py", line 35, in load_latest_param
> checkpoint = self.torchModelProcess.loadLatestModelWeight(latest_weights_path, self.model)
> File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/torch_model_process.py", line 56, in loadLatestModelWeight
> model.load_state_dict(checkpoint['model'])
> File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for MyModel:
> size mismatch for fcLayer_2.linear.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([100, 512]).
> size mismatch for fcLayer_2.linear.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([100]).
> @lpj0822
路径问题，已经修改

**Comment by lpj0822** [comment]
界面运行，在HV_YOLO中使用命令：
```
python3 easy_tools/easy_main.py
```

**Comment by lpj0822** [comment]
除了性能问题，其他问题已经修改
@foww-0001

**Comment by foww-0001** [comment]
运行界面上分类训练报错：
```
classify start train!
/home/wfw/EDGE/EdgeToolENV/bin/python3: No module named easyai.easy_ai
```
@lpj0822

**Comment by lpj0822** [comment]
已经修改，提交
@foww-0001

**Comment by foww-0001** [comment]
拉取最新代码，运行报错：
```
classify start train!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 85, in <module>
    train_main()
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 62, in train_main
    train_task.train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 26, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 90, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify_train.py", line 20, in __init__
    super().__init__(cfg_path, config_path, TaskName.Classify_Task)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/utility/base_train.py", line 32, in __init__
    "data_channel": self.train_task_config.image_channel
AttributeError: 'ClassifyConfig' object has no attribute 'image_channel'
```
修改base_train.py中"data_channel": self.train_task_config.image_channel的image_channel改为data_channel
@lpj0822

**Comment by foww-0001** [comment]
修改后继续运行，报错：
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 85, in <module>
    train_main()
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 62, in train_main
    train_task.train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 29, in train
    self.image_model_convert(task, task.model_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 38, in image_model_convert
    train_task.train_task_config.best_weights_file,
AttributeError: 'ClassifyConfig' object has no attribute 'best_weights_file'
```
修改train_task.train_task_config.best_weights_file中的best_weights_file改为best_weights_name。
分类修改后正常生成classnet.bin文件。

**Comment by foww-0001** [comment]
分割界面运行出错：
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 85, in <module>
    train_main()
  File "/home/wfw/EDGE/HV_YOLO/easyai/easy_ai.py", line 76, in train_main
    train_task.train(cfg_path, options.gpu_id, options.config_path, pretrain_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/train_task.py", line 28, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/seg/segment_train.py", line 76, in train
    self.test(val_path, epoch, save_model_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/seg/segment_train.py", line 144, in test
    self.segment_test.save_test_value(epoch, score, class_score)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/seg/segment_test.py", line 58, in save_test_value
    file.write(self.test_task_config.class_name[i][0] + ": {:.3f} ".format(iou))
AttributeError: 'SegmentionConfig' object has no attribute 'class_name'
```
修改file.write(self.test_task_config.class_name[i][0] + ": {:.3f} ".format(iou))中的class_name改为segment_class。
运行正常。
@lpj0822

**Comment by foww-0001** [comment]
注意到detect2d_config.py中的class_name改为detect2d_class，但是后面很多相关的class_name却没改过来。
相应的segment_config.py中的class_name改为segment_class，但是后面很多相关的class_name却没改过来。
@lpj0822

**Comment by lpj0822** [comment]
已经修改，代码提交
@foww-0001

**Comment by foww-0001** [comment]
detect界面测试，模型转换报错：
```
Usage: easy_convert.py [options]

easy_convert.py: error: Could not find the input file
```
@lpj0822

**Comment by lpj0822** [comment]
代码修改，提交
@foww-0001

**Comment by foww-0001** [comment]
拉取最新代码，界面分类，检测，分割训练模型没有问题。
@lpj0822
