### ISSUE TITLE
easyai develop分支代码测试

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/HV_YOLO#18]
1.测试分类、检测、分割上下位机精度与原先一样
2.测试tools
3.打包easyai
4.将客户使用软件的整体流程测试一遍，没有问题，将该分支代码作为初步稳定版本

**Comment by foww-0001** [comment]
Traceback (most recent call last):
  File "easyai/tools/compute_images_mean.py", line 57, in <module>
    main()
  File "easyai/tools/compute_images_mean.py", line 51, in main
    mean, std = test.compute(options.inputPath)
  File "easyai/tools/compute_images_mean.py", line 39, in compute
    numpy_images = np.stack(numpy_images)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/numpy/core/shape_base.py", line 422, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError

**Comment by foww-0001** [comment]
往往会搞不清楚imgdir指的是什么路径:
```
Usage: convert_segment_label.py [options]

This program

Options:
  -h, --help            show this help message and exit
  -i PATH, --input=PATH
                        images dir
  -c PATH, --config=PATH
                        config path
```
@lpj0822

**Comment by foww-0001** [comment]
convert_segment_label.py中convert_color_label结果有误，变成全白色图。config中的参数如下所示:
```
    "seg_label_type": 2,
    "segment_class": [
        [
            "background",
            "0,255,255"
        ],
        [
            "lane",
            "0,255,0"
        ]
    ],
```
@lpj0822

**Comment by foww-0001** [comment]
create_detection_anchors.py中没有参数输入，只能从代码中写入路径。
```
count: 0
Traceback (most recent call last):
  File "easyai/tools/create_detection_anchors.py", line 142, in <module>
    test()
  File "easyai/tools/create_detection_anchors.py", line 137, in test
    test.get_anchors(9)
  File "easyai/tools/create_detection_anchors.py", line 37, in get_anchors
    wh_numpy = self.get_width_height()
  File "easyai/tools/create_detection_anchors.py", line 61, in get_width_height
    return np.concatenate(result, axis=0)
ValueError: need at least one array to concatenate
```
@lpj0822

**Comment by foww-0001** [comment]
create_detection_sample.py中没有参数输入，只能从代码中写入路径。
且balance sample由于没有config配置文件输入带来不少问题。
class_name需改为detect2d_class：
```
Traceback (most recent call last):
  File "easyai/tools/create_detection_sample.py", line 85, in <module>
    test()
  File "easyai/tools/create_detection_sample.py", line 80, in test
    "/home/lpj/github/data/Berkeley/ImageSets", task_config.class_name)
AttributeError: 'MultiDet2dSegConfig' object has no attribute 'class_name'
```
@lpj0822

**Comment by foww-0001** [comment]
model_summary.py中没有参数输入，只能从代码中写入路径。
```
Traceback (most recent call last):
  File "easyai/tools/model_summary.py", line 19, in <module>
    main()
  File "easyai/tools/model_summary.py", line 13, in main
    model = model_factory.get_model(model_config)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 28, in get_model
    result = self.get_model_from_cfg(input_name, model_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 42, in get_model_from_cfg
    model_define = self.modelParse.readCfgFile(cfg_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_parse.py", line 13, in readCfgFile
    file = open(cfgPath, 'r')
FileNotFoundError: [Errno 2] No such file or directory: './cfg/yolov3.cfg'
```

**Comment by foww-0001** [comment]
CreateSegmentionSample.py中没有参数输入，只能从代码中写入路径。

**Comment by foww-0001** [comment]
model_to_onnx.py运行报错：
```
Traceback (most recent call last):
  File "easyai/tools/model_to_onnx.py", line 51, in <module>
    converter.model_convert(options.model, options.weight_path, options.save_dir)
  File "easyai/tools/model_to_onnx.py", line 22, in model_convert
    data_channel = model_config.get('data_channel')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by lpj0822** [comment]
除了新建的issue，其他都修改

**Comment by foww-0001** [comment]
resnet18， 打印其block个数为9，
```
convBNActivationBlock_0
maxpool_1
down_residualBlock_2
residualBlock_3
down_residualBlock_4
residualBlock_5
down_residualBlock_6
residualBlock_7
down_residualBlock_8
residualBlock_9
```
而使用的时候
```
[baseNet]
name=resnet18

[route]
layers=8
```
出现差错。
精度比对在标准数据caltech257上：
原来layers=8：63%
现在layers=9：

**Comment by foww-0001** [comment]
跑classify inference报错：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 25, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/cls/classify.py", line 34, in process
    self.task_config.class_name):
  File "/home/wfw/EDGE/HV_YOLO/easyai/visualization/task_show/classify_show.py", line 19, in show
    font, 0.5, (0, 255, 0), 2)
TypeError: integer argument expected, got float
```
修改：
```
src_image.shape[0] * 0.1, src_image.shape[1] * 0.1
```
为：
```
int(src_image.shape[0] * 0.1), int(src_image.shape[1] * 0.1)
```

**Comment by foww-0001** [comment]
segment可视化报错：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 39, in <module>
    main()
  File "easyai/inference_task.py", line 34, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 25, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/seg/segment.py", line 47, in process
    self.task_config.class_name):
AttributeError: 'SegmentionConfig' object has no attribute 'class_name'
```
class_name改为segment_class
@lpj0822

**Comment by foww-0001** [comment]
### caltech257上下位机精度对比：
* resnet18
** PC 63.4%
** AMBA 61.7%

**Comment by foww-0001** [comment]
分割下位机运行结果报错：
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.6) /home/ypchang/rpmbuild/BUILD/opencv-3.4.6/modules/imgproc/src/resize.cpp:3721: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

Aborted (core dumped)
```
@lpj0822

**Comment by foww-0001** [comment]
继续运行报错：
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.6) /home/ypchang/rpmbuild/BUILD/opencv-3.4.6/modules/imgcodecs/src/loadsave.cpp:687: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

Aborted (core dumped)
```
@lpj0822

**Comment by foww-0001** [comment]
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 51, in <module>
    main()
  File "easyai/train_task.py", line 46, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 25, in train
    if REGISTERED_TRAIN_TASK.has_class(self.task_name):
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 32, in has_class
    result = key.strip() in self._module_dict
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by lpj0822** [comment]
上一条issue是怎么回事

**Comment by foww-0001** [comment]
### develop测试内容
* easy_tool的对外接口测试，训练分类，检测，分割
* 分类，检测，分割对应inference的测试精度（offline）
* 转换到下位机模型进行精度测试（offline）
@lpj0822

**Comment by lpj0822** [comment]
easy_tools/test_gui.py

**Comment by foww-0001** [comment]
运行python3 easy_tools/easyai_gui.py报错：
```
classify start train!
Usage: easy_ai.py [options]

easy_ai.py: error: Could not find the input train file
```
确认数据没有问题。
@lpj0822

**Comment by lpj0822** [comment]
改了

**Comment by lpj0822** [comment]
easy_tools/train_scripts里的.log改为log

**Comment by foww-0001** [comment]
运行报错：
```
RuntimeError: Error(s) in loading state_dict for ClassNet:
	Missing key(s) in state_dict: 
```

**Comment by foww-0001** [comment]
更新模型后，运行报错：
```
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/SpatialAdaptiveAveragePooling.cu line=165 error=59 : device-side assert triggered

/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
对于100类的模型无法进行训练，对于两类的猫狗，虽然可以训练，但是loss结果不对。

**Comment by foww-0001** [comment]
Traceback (most recent call last):
  File "easyai/tools/model_tool/model_net_show.py", line 18, in <module>
    show = ModelNetShow()
NameError: name 'ModelNetShow' is not defined
@lpj0822

**Comment by foww-0001** [comment]
```
baseNet_0
base_convBNActivationBlock_0.block.convolutional.weight True
base_convBNActivationBlock_0.block.bn2d.weight True
base_convBNActivationBlock_0.block.bn2d.bias True
base_convBNActivationBlock_1.block.convolutional.weight True
base_convBNActivationBlock_1.block.bn2d.weight True
base_convBNActivationBlock_1.block.bn2d.bias True
base_convBNActivationBlock_2.block.convolutional.weight True
base_convBNActivationBlock_2.block.bn2d.weight True
base_convBNActivationBlock_2.block.bn2d.bias True
base_convBNActivationBlock_3.block.convolutional.weight True
base_convBNActivationBlock_3.block.bn2d.weight True
base_convBNActivationBlock_3.block.bn2d.bias True
base_convBNActivationBlock_4.block.convolutional.weight True
base_convBNActivationBlock_4.block.bn2d.weight True
base_convBNActivationBlock_4.block.bn2d.bias True
base_convBNActivationBlock_5.block.convolutional.weight True
base_convBNActivationBlock_5.block.bn2d.weight True
base_convBNActivationBlock_5.block.bn2d.bias True
base_convBNActivationBlock_6.block.convolutional.weight True
base_convBNActivationBlock_6.block.bn2d.weight True
base_convBNActivationBlock_6.block.bn2d.bias True
base_convBNActivationBlock_7.block.convolutional.weight True
base_convBNActivationBlock_7.block.bn2d.weight True
base_convBNActivationBlock_7.block.bn2d.bias True
base_convBNActivationBlock_8.block.convolutional.weight True
base_convBNActivationBlock_8.block.bn2d.weight True
base_convBNActivationBlock_8.block.bn2d.bias True
base_convBNActivationBlock_10.block.convolutional.weight True
base_convBNActivationBlock_10.block.bn2d.weight True
base_convBNActivationBlock_10.block.bn2d.bias True
base_convBNActivationBlock_11.block.convolutional.weight True
base_convBNActivationBlock_11.block.bn2d.weight True
base_convBNActivationBlock_11.block.bn2d.bias True
base_convBNActivationBlock_12.block.convolutional.weight True
base_convBNActivationBlock_12.block.bn2d.weight True
base_convBNActivationBlock_12.block.bn2d.bias True
base_convBNActivationBlock_13.block.convolutional.weight True
base_convBNActivationBlock_13.block.bn2d.weight True
base_convBNActivationBlock_13.block.bn2d.bias True
base_convBNActivationBlock_14.block.convolutional.weight True
base_convBNActivationBlock_14.block.bn2d.weight True
base_convBNActivationBlock_14.block.bn2d.bias True
base_convBNActivationBlock_15.block.convolutional.weight True
base_convBNActivationBlock_15.block.bn2d.weight True
base_convBNActivationBlock_15.block.bn2d.bias True
base_convBNActivationBlock_17.block.convolutional.weight True
base_convBNActivationBlock_17.block.bn2d.weight True
base_convBNActivationBlock_17.block.bn2d.bias True
base_convBNActivationBlock_18.block.convolutional.weight True
base_convBNActivationBlock_18.block.bn2d.weight True
base_convBNActivationBlock_18.block.bn2d.bias True
base_convBNActivationBlock_19.block.convolutional.weight True
base_convBNActivationBlock_19.block.bn2d.weight True
base_convBNActivationBlock_19.block.bn2d.bias True
base_convBNActivationBlock_21.block.convolutional.weight True
base_convBNActivationBlock_21.block.bn2d.weight True
base_convBNActivationBlock_21.block.bn2d.bias True
base_convBNActivationBlock_22.block.convolutional.weight True
base_convBNActivationBlock_22.block.bn2d.weight True
base_convBNActivationBlock_22.block.bn2d.bias True
base_convBNActivationBlock_23.block.convolutional.weight True
base_convBNActivationBlock_23.block.bn2d.weight True
base_convBNActivationBlock_23.block.bn2d.bias True
base_convBNActivationBlock_24.block.convolutional.weight True
base_convBNActivationBlock_24.block.bn2d.weight True
base_convBNActivationBlock_24.block.bn2d.bias True
base_convBNActivationBlock_25.block.convolutional.weight True
base_convBNActivationBlock_25.block.bn2d.weight True
base_convBNActivationBlock_25.block.bn2d.bias True
base_convBNActivationBlock_26.block.convolutional.weight True
base_convBNActivationBlock_26.block.bn2d.weight True
base_convBNActivationBlock_26.block.bn2d.bias True
base_convBNActivationBlock_28.block.convolutional.weight True
base_convBNActivationBlock_28.block.bn2d.weight True
base_convBNActivationBlock_28.block.bn2d.bias True
base_convBNActivationBlock_29.block.convolutional.weight True
base_convBNActivationBlock_29.block.bn2d.weight True
base_convBNActivationBlock_29.block.bn2d.bias True
base_convBNActivationBlock_30.block.convolutional.weight True
base_convBNActivationBlock_30.block.bn2d.weight True
base_convBNActivationBlock_30.block.bn2d.bias True
base_convBNActivationBlock_32.block.convolutional.weight True
base_convBNActivationBlock_32.block.bn2d.weight True
base_convBNActivationBlock_32.block.bn2d.bias True
base_convBNActivationBlock_33.block.convolutional.weight True
base_convBNActivationBlock_33.block.bn2d.weight True
base_convBNActivationBlock_33.block.bn2d.bias True
base_convBNActivationBlock_34.block.convolutional.weight True
base_convBNActivationBlock_34.block.bn2d.weight True
base_convBNActivationBlock_34.block.bn2d.bias True
base_convBNActivationBlock_36.block.convolutional.weight True
base_convBNActivationBlock_36.block.bn2d.weight True
base_convBNActivationBlock_36.block.bn2d.bias True
base_convBNActivationBlock_37.block.convolutional.weight True
base_convBNActivationBlock_37.block.bn2d.weight True
base_convBNActivationBlock_37.block.bn2d.bias True
base_convBNActivationBlock_38.block.convolutional.weight True
base_convBNActivationBlock_38.block.bn2d.weight True
base_convBNActivationBlock_38.block.bn2d.bias True
base_convBNActivationBlock_39.block.convolutional.weight True
base_convBNActivationBlock_39.block.bn2d.weight True
base_convBNActivationBlock_39.block.bn2d.bias True
base_convBNActivationBlock_40.block.convolutional.weight True
base_convBNActivationBlock_40.block.bn2d.weight True
base_convBNActivationBlock_40.block.bn2d.bias True
base_convBNActivationBlock_41.block.convolutional.weight True
base_convBNActivationBlock_41.block.bn2d.weight True
base_convBNActivationBlock_41.block.bn2d.bias True
base_convBNActivationBlock_43.block.convolutional.weight True
base_convBNActivationBlock_43.block.bn2d.weight True
base_convBNActivationBlock_43.block.bn2d.bias True
base_convBNActivationBlock_44.block.convolutional.weight True
base_convBNActivationBlock_44.block.bn2d.weight True
base_convBNActivationBlock_44.block.bn2d.bias True
base_convBNActivationBlock_45.block.convolutional.weight True
base_convBNActivationBlock_45.block.bn2d.weight True
base_convBNActivationBlock_45.block.bn2d.bias True
base_convBNActivationBlock_47.block.convolutional.weight True
base_convBNActivationBlock_47.block.bn2d.weight True
base_convBNActivationBlock_47.block.bn2d.bias True
base_convBNActivationBlock_48.block.convolutional.weight True
base_convBNActivationBlock_48.block.bn2d.weight True
base_convBNActivationBlock_48.block.bn2d.bias True
base_convBNActivationBlock_49.block.convolutional.weight True
base_convBNActivationBlock_49.block.bn2d.weight True
base_convBNActivationBlock_49.block.bn2d.bias True
base_convBNActivationBlock_50.block.convolutional.weight True
base_convBNActivationBlock_50.block.bn2d.weight True
base_convBNActivationBlock_50.block.bn2d.bias True
base_convBNActivationBlock_51.block.convolutional.weight True
base_convBNActivationBlock_51.block.bn2d.weight True
base_convBNActivationBlock_51.block.bn2d.bias True
base_convBNActivationBlock_52.block.convolutional.weight True
base_convBNActivationBlock_52.block.bn2d.weight True
base_convBNActivationBlock_52.block.bn2d.bias True
base_convBNActivationBlock_54.block.convolutional.weight True
base_convBNActivationBlock_54.block.bn2d.weight True
base_convBNActivationBlock_54.block.bn2d.bias True
base_convBNActivationBlock_55.block.convolutional.weight True
base_convBNActivationBlock_55.block.bn2d.weight True
base_convBNActivationBlock_55.block.bn2d.bias True
base_convBNActivationBlock_56.block.convolutional.weight
 True
base_convBNActivationBlock_56.block.bn2d.weight True
base_convBNActivationBlock_56.block.bn2d.bias True
base_convBNActivationBlock_58.block.convolutional.weight True
base_convBNActivationBlock_58.block.bn2d.weight True
base_convBNActivationBlock_58.block.bn2d.bias True
base_convBNActivationBlock_59.block.convolutional.weight True
base_convBNActivationBlock_59.block.bn2d.weight True
base_convBNActivationBlock_59.block.bn2d.bias True
base_convBNActivationBlock_60.block.convolutional.weight True
base_convBNActivationBlock_60.block.bn2d.weight True
base_convBNActivationBlock_60.block.bn2d.bias True
```
base_convBNActivationBlock_38之前的层未被置为False。

**Comment by lpj0822** [comment]
代码已经修改

**Comment by foww-0001** [comment]
freeze layer没有问题，但是精度在0.5不发生变化，如果不freeze layer反而精度可以达到0.7。
```
Overall Acc: 	 0.9987693112327004
Mean Acc : 	 0.5017984716780363
FreqW Acc : 	 0.9975473439193716
Mean IoU : 	 0.5011761838377626
Val epoch loss: 0.04992389678955078
```
@lpj0822

**Comment by foww-0001** [comment]
运行test_gui.py中的segnet测试，报错：
```
Traceback (most recent call last):
  File "/home/wfw/EDGE/HV_YOLO/easy_tools/accuracy_test/accuracy_test_thread.py", line 48, in run
    self.test.pc_test(self.model_name, self.weight_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/offline_evaluation.py", line 46, in pc_test
    inference_task.infer(model_name, 0, weight_path, self.config_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/inference_task.py", line 24, in infer
    task = build_from_cfg(task_args, REGISTERED_INFERENCE_TASK)
  File "/home/wfw/EDGE/HV_YOLO/easyai/utility/registry.py", line 90, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tasks/seg/segment.py", line 23, in __init__
    self.model = self.torchModelProcess.initModel(self.model_args, gpu_id)
  File "/home/wfw/EDGE/HV_YOLO/easyai/torch_utility/torch_model_process.py", line 23, in initModel
    model = self.modelFactory.get_model(model_config)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 30, in get_model
    result = self.get_model_from_cfg(input_name, model_args)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_factory.py", line 44, in get_model_from_cfg
    model_define = self.modelParse.readCfgFile(cfg_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/model/utility/model_parse.py", line 13, in readCfgFile
    file = open(cfgPath, 'r')
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/wfw/EDGE/HV_YOLO/easy_tools/accuracy_test/./data/segnet.cfg'
```
@lpj0822

**Comment by lpj0822** [comment]
问题已经修改
@foww-0001

**Comment by foww-0001** [comment]
运行test_gui.py中的classnet测试下位机结果，报错：
paramater error.
原因未知。
@lpj0822

**Comment by foww-0001** [comment]
运行test_gui.py中的classnet测试PC and ARM的结果，报错：
error.
原因未知。
@lpj0822

**Comment by foww-0001** [comment]
### detnet测试
运行test_gui.py中的detnet测试PC的结果，结果正常，如下：
```
pc
Mean AP = 0.9875
Results:
pear: 0.992
apple: 0.958
orange: 0.999
potato: 1.000
```

运行ARM测试则出现报错：
```
Traceback (most recent call last):
  File "/home/wfw/EDGE/HV_YOLO/easy_tools/accuracy_test/accuracy_test_thread.py", line 50, in run
    self.test.arm_test()
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/offline_evaluation.py", line 57, in arm_test
    self.target_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/offline_test/offline_det2d_evaluation.py", line 22, in process
    mAP, aps = self.evaluator.result_eval(test_path, target_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 43, in result_eval
    recall, precision, ap = self.calculate_ap(gt_boxes, detect_boxes, 0.5)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 103, in calculate_ap
    tp, fp, iou = self.get_tp_fp(image_ids, class_recs, boxes, iou_thresh)
  File "/home/wfw/EDGE/HV_YOLO/easyai/evaluation/calculate_mAp.py", line 182, in get_tp_fp
    R = class_recs[image_ids[d]]
KeyError: 'f79.jpgapple 0.996194 237.946 53.0196 325.584 147.137'

```
@lpj0822

**Comment by lpj0822** [comment]
对于det2d测试上下位机精度，需要修改上下位机代码，主要是修改识别的类别

**Comment by foww-0001** [comment]
问题：FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/wfw/EDGE/HV_YOLO/easy_tools/accuracy_test/./data/segnet.cfg'
```
修改完相应路径以后（pc_arm_window.py），修改如下：
```
74    cfg_path = os.path.join(dir_name, "../data/segnet.cfg")
```
继续运行，报错：
```
Traceback (most recent call last):
  File "/home/wfw/EDGE/HV_YOLO/easy_tools/accuracy_test/accuracy_test_thread.py", line 48, in run
    self.test.pc_test(self.model_name, self.weight_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/offline_evaluation.py", line 48, in pc_test
    self.target_path)
  File "/home/wfw/EDGE/HV_YOLO/easyai/tools/offline_test/offline_segment_evaluation.py", line 35, in process
    test_path = os.path.join(test_dir, filename_post)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
已放弃 (核心已转储)
```

**Comment by lpj0822** [comment]
改了，代码提交
@foww-0001
